AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ConnectInstanceARN:
    Type: String
    Description: Please enter the full ARN of the existing Amazon Connect Instance
    AllowedPattern: ".+"
    ConstraintDescription: ConnectInstanceARN parameter cannot be blank
  
  CreatePhoneNumber:
    Description: If you want this template to create an AWS Connect phone number please select. If you already have a phone number, you can use it with your flow
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No
  
Conditions:
  CreatePhoneNumberCondition: !Equals [!Ref CreatePhoneNumber, Yes]

Resources:
  # Toll free number to use with the flow.
  PhoneNumber:
    Type: 'AWS::Connect::PhoneNumber'
    Condition: CreatePhoneNumberCondition
    Properties:
      TargetArn: !Ref ConnectInstanceARN
      Description: VoiceFoundry demo phone number
      Type: TOLL_FREE
      CountryCode: US

  # Demo contact flow with sample content in it.
  # The contact flow here is a placeholder. After creating the flow the content of it should be updated manually.
  DemoContactFlow:
    Type: "AWS::Connect::ContactFlow"
    Properties:
      Name: Voice Foundry Demo ContactFlow
      Description: This demo flow has been created as a placeholder. Please replace it with the actual flow by importing the JSON file in the project
      InstanceArn: !Ref ConnectInstanceARN
      Type: CONTACT_FLOW
      Content: '{"Version":"2019-10-30","StartAction":"32e5247f-7929-44f5-93f5-605ce2317b2c","Actions":[{"Identifier":"32e5247f-7929-44f5-93f5-605ce2317b2c","Type":"MessageParticipant","Transitions":{"NextAction":"5fa06901-2fc6-4056-a698-97cfb7c6782a","Errors":[],"Conditions":[]},"Parameters":{"Text":"Thanks for calling the basic flow!"}},{"Identifier":"5fa06901-2fc6-4056-a698-97cfb7c6782a","Type":"DisconnectParticipant","Transitions":{},"Parameters":{}}]}'
