AWSTemplateFormatVersion: 2010-09-09

Resources:
  # DynamoDB table to hold the records of the call and generated vanity numbers
  vanityNumbersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      #TableName: vanityNumbers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: phoneNumber
          AttributeType: S
        - AttributeName: recordDate
          AttributeType: N
      KeySchema:
        - AttributeName: phoneNumber
          KeyType: HASH
        - AttributeName: recordDate
          KeyType: RANGE

Outputs:
  DatabaseName:
    Description: The name of the DynamoDB created
    Value: !Ref vanityNumbersTable