AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ConnectInstanceARN:
    Type: String
    Description: Please enter the full ARN of the existing Amazon Connect Instance
    AllowedPattern: ".+"
    ConstraintDescription: ConnectInstanceARN parameter cannot be blank
  CreatePhoneNumber:
    Description: If you want this template to create an AWS Connect phone number please select. If you already have a phone number, you can use it with your flow
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No

Conditions:
  CreatePhoneNumberCondition: !Equals [!Ref CreatePhoneNumber, Yes]

Resources:
  # This bucket will be used when deploying manually from local computer
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - "voicefoundry-artifacts"
          - !Select [ 0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]], ]

  ConnectObjects:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://voicefoundry-artifacts.s3.us-east-1.amazonaws.com/CloudFormation/ConnectObjects.yaml"
      Parameters:
        ConnectInstanceARN: !Ref ConnectInstanceARN
        CreatePhoneNumber: !Ref CreatePhoneNumber

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://voicefoundry-artifacts.s3.us-east-1.amazonaws.com/CloudFormation/DatabaseStack.yaml"

  LambdaFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://voicefoundry-artifacts.s3.us-east-1.amazonaws.com/CloudFormation/LambdaFunctions.yaml"
      Parameters:
        DynamoDBName: !GetAtt DatabaseStack.Outputs.DatabaseName

# Output parameters
Outputs:
  WebpageURL:
    Description: The URL of the dynamic webpage to display last 5 calls to the flow
    Value: !GetAtt LambdaFunctions.Outputs.WebpageURL
  LambdaARN:
    Description: The ARN of the Lambda function that is going to be used in ContactFlow
    Value: !GetAtt LambdaFunctions.Outputs.LambdaARN
  ArtifactsBucket:
    Description: If you want to deploy Lambda functions on your own. You can use this bucket in package.json files
    Value: !Ref ArtifactsBucket
  VanityNumbersLambdaFunctionName:
    Description: The name of the vanity number Lambda function. You can use this value to manually publish this function
    Value: !GetAtt LambdaFunctions.Outputs.WebpageLambdaFunctionName
  WebpageLambdaFunctionName:
    Description: The name of the webpage Lambda function. You can use this value to manually publish this function
    Value: !GetAtt LambdaFunctions.Outputs.WebpageLambdaFunctionName
  PhoneNumber:
    Description: Phone number created
    Condition: CreatePhoneNumberCondition
    Value: !Ref ConnectObjects.Outputs.PhoneNumber