AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ConnectInstanceARN:
    Type: String
    Description: Please enter the full ARN of the existing Amazon Connect Instance

# Region mappings for artifact buckets so that the Cloudformation template
# can create lambda function on all the regions that supports Amazon Connect
Mappings:
  RegionMap:
    us-east-1:
      bucketname: voicefoundry-artifacts-us-east-1
    us-west-2:
      bucketname: voicefoundry-artifacts-us-west-2
    af-south-1:
      bucketname: voicefoundry-artifacts-af-south-1
    ap-northeast-2:
      bucketname: voicefoundry-artifacts-ap-northeast-2
    ap-southeast-1:
      bucketname: voicefoundry-artifacts-ap-southeast-1
    ap-southeast-2:
      bucketname: voicefoundry-artifacts-ap-southeast-2
    ap-northeast-1:
      bucketname: voicefoundry-artifacts-ap-northeast-1
    ca-central-1:
      bucketname: voicefoundry-artifacts-ca-central-1
    eu-central-1:
      bucketname: voicefoundry-artifacts-eu-central-1
    eu-west-2:
      bucketname: voicefoundry-artifacts-eu-west-2

Resources:
  # This bucket will be used when deploying manually from locak computer
  ArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
        - "-"
        - - "voicefoundry-artifacts"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  # DynamoDB tablo to hold the records of the call and generated vanity numbers
  vanityNumbersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: vanityNumbers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: phoneNumber
          AttributeType: S
        - AttributeName: recordDate
          AttributeType: N
      KeySchema:
        - AttributeName: phoneNumber
          KeyType: HASH
        - AttributeName: recordDate
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

  # Toll free number to use with the flow. Since AWS free tier has some glitch, this part has been commented-out
  # PhoneNumber:
  #   Type: 'AWS::Connect::PhoneNumber'
  #   Properties:
  #     TargetArn: !Ref ConnectInstanceARN
  #     Description: Toll free number to use with the flow.
  #     Type: TOLL_FREE
  #     CountryCode: US

  # Demo contact flow with sample content in it.
  # Since creating the content of the contact flows is somehow problematic the content should be imported manually.
  DemoContactFlow:
    Type: "AWS::Connect::ContactFlow"
    Properties:
      Name: Voice Foundry Demo ContactFlow
      Description: This demo flow has been created as a placeholder. Please replate it with the actual flow by importing the JSON file
      InstanceArn: !Ref ConnectInstanceARN
      Type: CONTACT_FLOW
      Content: '{"Version":"2019-10-30","StartAction":"32e5247f-7929-44f5-93f5-605ce2317b2c","Actions":[{"Identifier":"32e5247f-7929-44f5-93f5-605ce2317b2c","Type":"MessageParticipant","Transitions":{"NextAction":"5fa06901-2fc6-4056-a698-97cfb7c6782a","Errors":[],"Conditions":[]},"Parameters":{"Text":"Thanks for calling the basic flow!"}},{"Identifier":"5fa06901-2fc6-4056-a698-97cfb7c6782a","Type":"DisconnectParticipant","Transitions":{},"Parameters":{}}]}'

  # The role required for the Lambda functions
  VoiceFoundryLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: voicefoundry-lambda-role
      Description: VoiceFoundry Lambda execution role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: voicefoundry-inline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:*"
                  - "dynamodb:*"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  # The function that generates possible vanity numbers, stores top 5 to the DynamoDB and returns top 3 to the caller flow
  # The zip file is taken from the corresponding artifact bucket in the same region
  VanityNumbersLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: generate-vanity-numbers-ts
      Handler: index.handler
      Role: !GetAtt VoiceFoundryLambdaRole.Arn
      Code:
        S3Bucket: !FindInMap [RegionMap, !Ref "AWS::Region", bucketname]
        S3Key: generate-vanity-numbers-ts.zip
      Runtime: nodejs14.x
      Timeout: 3

  # Permission required for Amazon Connect to run the Lambda function
  VanityNumbersConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VanityNumbersLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "connect.amazonaws.com"

  # Puplic Lambda function that returns a web page as a response that includes last 5 calls to the service
  # The zip file is taken from the corresponding artifact bucket in the same region
  WebpageLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: webpage-ts
      Handler: app.lambdaHandler
      Role: !GetAtt VoiceFoundryLambdaRole.Arn
      Code:
        S3Bucket: !FindInMap [RegionMap, !Ref "AWS::Region", bucketname]
        S3Key: webpage-ts.zip
      Runtime: nodejs14.x
      Timeout: 3

  # Adding a URL to the Lambda function
  WebpageFunctionURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt WebpageLambdaFunction.Arn

  # Permissions to reach the URL from public
  LambdaFunctionURLPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebpageLambdaFunction
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

# Output parameters
Outputs:
  WebpageURL:
    Description: The URL of the dynamic webpage to display last 5 calls to the flow
    Value: !GetAtt WebpageFunctionURL.FunctionUrl
  LambdaARN:
    Description: The ARN of the Lambda function that is going to be used in ContactFlow
    Value: !GetAtt VanityNumbersLambdaFunction.Arn
  ArtifactsBucket:
    Description: If you want to deploy Lambda functions on your own. You can use this bucket in package.json files
    Value: !Ref ArtifactsBucket
